[package]
name = "monistode-assemblers"
version = "0.1.7"
edition = "2021"
description = "A collection of assemblers for the monistode set of architectures."
license = "MIT"

[dependencies]
bitvec = "1.0.1"
combine = "4.6.7"
monistode-binutils = "0.1.4"
monistode-macros = "0.1.7"
